yt-events-main/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('events.urls')),
    path("hashtags/", include('hashtags.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yt-events-main/events/urls.py
from audioop import add
from django.urls import path
from . views import home,add_new_event
urlpatterns = [
    path("", home,name='home'),
    path("category/<str:category>/",home,name="home-category"),
    path("new/",add_new_event,name="new")
]

yt-events-main/hashtags/urls.py
from django.urls import path
from . views import home, follow, feedback

app_name = 'hashtags'

urlpatterns = [
    path("<str:hashtag>/", home,name='home'),
    path("<str:hashtag>/follow/",follow ,name='follow'),
    path("<str:hashtag>/feedback/",feedback ,name='feedback'),
]

yt-events-main/events/models.py
from django.db import models
from hashtags.models import Hashtag

# Create your models here.

class Event(models.Model):
    category_choices = (
        ('tech-talks','Tech Talks'),
        ('freelancing','Freelancing'),
        ('content-creation','Content Creations'),
        ('finance','Finance'),
        ('entrepreneurship','Entrepreneurship'),
     
    )
    title = models.CharField(max_length = 255)
    video_id =models.CharField( max_length=50)
    thumbnail = models.ImageField(upload_to = "thumbnail/%Y/%m/")
    is_active = models.BooleanField(default = True)
    category = models.CharField(max_length=100,choices=category_choices)
    scheduled_on = models.DateTimeField()
    
    hashtags = models.ManyToManyField(Hashtag, blank=True)
    
    def __str__(self):
        return f'{self.title} - {self.scheduled_on}'

yt-events-main/hashtags/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Hashtag(models.Model):
    title = models.CharField("hashtag name", max_length=100)
    is_active = models.BooleanField(default=False)


    def __str__(self) :
        return self.title


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    hashtags_followed = models.ManyToManyField(Hashtag, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.hashtags_followed.all()}"


class Feedback(models.Model):
    FEEDBACK_CHOICES = (
        ('IP', "Intellectual Property Violation"),
        ('VODO', "Violence or Dangerous organizations"),
        ('BOH', "Bullying or Harassment"),
    )
    text = models.CharField(max_length=200, choices=FEEDBACK_CHOICES)
    hashtag = models.ForeignKey(Hashtag, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.hashtag.title} - {self.text} "



    

yt-events-main/events/forms.py
from django import forms
from django import forms
from . models import Event

class EventForm(forms.ModelForm):
    new_tags = forms.CharField(label="Add new tags seperated by commas",max_length=2000)
    class Meta:
        model = Event
        fields = "__all__"
        widgets = {
            "scheduled_on":forms.DateInput(
                attrs= {
                    "class": "form-control ",
                     "type":'datetime-local'
                }
            )
        }

yt-events-main/hashtags/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('text',)
        

yt-events-main/events/views.py
from django.shortcuts import redirect, render
from . models import Event
import datetime
from . forms import EventForm
from hashtags.models import Hashtag
# Create your views here.

def home(request,category = None):
    upcoming_events = Event.objects.all().filter(scheduled_on__gte = datetime.date.today()).order_by('scheduled_on')[:2]
    past_events = Event.objects.all().filter(scheduled_on__lte = datetime.date.today(), is_active = True).order_by('scheduled_on')
    if category is not None:
        past_events = Event.objects.all().filter(scheduled_on__lte = datetime.date.today(), is_active = True,category=category).order_by('-scheduled_on')
    context = {
        "upcoming_events":upcoming_events,
        "past_events":past_events
    }
    return render(request, 'index.html',context)

def add_new_event(request):
    form = EventForm()
    if request.method == "POST":
        new_tags = request.POST["new_tags"]
        tags = new_tags.split(',')
        for tag in tags:
            if not Hashtag.objects.filter(title=tag):
                Hashtag.objects.create(title=tag)
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    context = {
        "form":form
    }
    return render(request, 'add_event.html',context)

yt-events-main/hashtags/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Hashtag, Profile, Feedback
from events.models import Event
from .forms import FeedbackForm

# Create your views here.


def home(request, hashtag):
    form = FeedbackForm()
    hashtag = get_object_or_404(Hashtag, title=hashtag)
    user_profile = Profile.objects.get(user=request.user)
    queryset = user_profile.hashtags_followed.all().filter(title=hashtag.title)
    follow=False
    if queryset:
        follow=True
    events = Event.objects.filter()
    return render(request, 'hashtags/home.html', {'hashtag':hashtag, 'follow':follow, 'form' : form})


def follow(request, hashtag):
    hashtag = get_object_or_404(Hashtag, title=hashtag)
    user_profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        queryset = user_profile.hashtags_followed.all().filter(title=hashtag.title)
        if queryset:
            user_profile.hashtags_followed.remove(hashtag)
        else:
            user_profile.hashtags_followed.add(hashtag)
        return redirect('hashtags:home', hashtag)

def feedback(request, hashtag):
    hashtag = get_object_or_404(Hashtag, title=hashtag)
    if request.method == "POST":
        Feedback.objects.create(text = request.POST['text'], hashtag=hashtag)
        return redirect('hashtags:home' , hashtag)            

    

yt-events-main/hashtags/templates/hashtags/home.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="{% static 'hashtags/styles.css' %}" rel="stylesheet" type="text/css">
    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>

<body>
    <!-- {% include 'includes/navbar.html' %} -->

    <div class="container hashtagpage_container">
        <div>
            <h2 class="m-3">
                {{hashtag.title}}

            </h2>
        </div>
        <div class="hashtagpage_btns">
            <form action="{% url 'hashtags:follow' hashtag %}" method="post">
                {% csrf_token %}
                {% if follow %}
                <button type="submit" class="btn btn-outline-primary py-2 px-3 m-2">Unfollow<i
                        class="fa-solid fa-check mx-1"></i></button>
                {% else %}
                <button type="submit" class="btn btn-outline-primary py-2 px-3 m-2">Follow<i
                        class="fa-solid fa-check mx-1"></i></button>
                {% endif %}
            </form>



            <!-- Button trigger modal -->
            <button type="button" class="btn btn-outline-danger py-2  px-3 my-2" data-bs-toggle="modal"
                data-bs-target="#exampleModal">
                Report <i class="fa-solid fa-flag"></i>
            </button>


            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Give your Feedback</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form action="{% url 'hashtags:feedback' hashtag %}" method="POST">
                            <div class="modal-body">

                                {% csrf_token %}
                                {{ form|crispy }}

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Submit Feedback</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>



        </div>

    </div>

    <div class="container m-5">
        <div class="row">


            {% for event in hashtag.event_set.all %}
            <div class="col-md-4 col-sm-12 mx-auto ">
                <div class="card float-md-end card my-2 mx-auto" style="width: 20rem">
                    <img src="https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg" class="card-img-top"
                        alt="..." style="height: 10rem; object-fit: cover" />
                    <div class="card-body">
                        <h6 class="card-title" style="height: 3rem; overflow: hidden">
                            {{event.title }}
                        </h6>
                        <h6>
                            <div class="d-grid gap-2">
                                <button type="button" class="btn btn-outline-primary rounded-pill"
                                    data-bs-toggle="modal" data-bs-target="#videoModal"
                                    onClick="playvideo({{events.id | safe}})">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-youtube" viewBox="0 0 16 16">
                                        <path
                                            d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z" />
                                    </svg>
                                    <span class="ms-1">Watch Now</span>
                                </button>
                            </div>
                        </h6>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>



</body>

</html>

yt-events-main/hashtags/templates/hashtags/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
	<div class="container px-4">
		<a class="navbar-brand" href="{% url 'home' %}">Events</a>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarResponsive"
			aria-controls="navbarResponsive"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ms-auto">
				{% comment %}
				<li class="nav-item">
					<a class="nav-link" href="#">About</a>
				</li>
				{% endcomment %}
				<li class="nav-item text-white">
					<a class="nav-link" href="{% url 'new' %}">
						<span
							><svg
								xmlns="http://www.w3.org/2000/svg"
								width="24"
								height="24"
								fill="currentColor"
								class="bi bi-plus"
								viewBox="0 0 16 16"
							>
								<path
									d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"
								/></svg
						></span>
						Add Event</a
					>
				</li>
			</ul>
		</div>
	</div>
</nav>

yt-events-main/templates/add_event.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="container mt-5">
	<div class="row">
		<div class="col-lg-12 col-xl-12 mx-auto">
			<div class="card card-body my-5 shadow rounded">
				<form action="{% url 'new' %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form|crispy }}
			
					<button type="submit" class="btn btn-outline-primary rounded-pill">
						Schedule
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

yt-events-main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
		/>
		<meta name="description" content="" />
		<meta name="author" content="" />
		<title>YouTube Events</title>
		<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
		<!-- Core theme CSS (includes Bootstrap)-->
		<link href="{% static 'css/styles.css' %}" rel="stylesheet" />
	</head>
	<body id="page-top">
		<!-- Navigation-->
		{% include 'includes/navbar.html' %}
		
        {% block content %}{% endblock content %}

		<!-- Footer-->
		{% include 'includes/footer.html' %}
		<!-- Bootstrap core JS-->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
		<!-- Core theme JS-->
		<!-- <script src="js/scripts.js"></script> -->
		<script type="text/javascript">
			const btn = document.querySelector(".close-btn");
			btn.addEventListener("click", stop);
			function stop() {
				let video = document.getElementById("video");
				video.contentWindow.postMessage(
					'{"event":"command", "func":"stopVideo", "args":""}',
					"*"
				);
				document.getElementById("video").src = ""
			}
		</script>
		{% block script %}{% endblock script %}
	</body>
</html>

yt-events-main/templates/includes/footer.html
<footer class="py-5 bg-dark">
    <div class="container px-4">
        <p class="m-0 text-center text-white">Copyright &copy; Events 2022</p>
    </div>
</footer>

yt-events-main/templates/index.html
{% extends 'base.html' %} {% block content %}
<!-- Header-->
<header class="bg-primary bg-gradient text-white">
	<div class="container px-4 text-center">
		<h1 class="fw-bolder">Welcome To Events</h1>
		<p class="lead">One and Only Place To Watch YouTube Events</p>
	</div>
	<div class="upcoming-event"></div>
</header>

<!-- events -->
<section id="" class="p-0 my-5">
	<div class="upcoming-events">
		<div class="container">
			<div class="row">
				<h1 class="fw-bolder text-center my-4">Upcoming Event.</h1>
				{% for events in upcoming_events %}
				<div class="col-md-6 col-sm-12 mx-auto">
					<div
						class="{% if forloop.first %}card float-md-end card my-2 mx-auto {% else %}card my-2 mx-auto float-md-start{% endif %}"
						style="width: 20rem"
					>
						<img
							src="{{events.thumbnail.url}}"
							class="card-img-top"
							alt="..."
							style="height: 10rem; object-fit: cover"
						/>
						<div class="card-body">
							<h6 class="card-title" style="height: 3rem; overflow: hidden">
								{{events.title | truncatewords:7}}
							</h6>
							<h6>
								<a href="#" class="text-decoration-none text-secondary">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="16"
										height="16"
										fill="currentColor"
										class="bi bi-calendar-check-fill"
										viewBox="0 0 16 16"
									>
										<path
											d="M4 .5a.5.5 0 0 0-1 0V1H2a2 2 0 0 0-2 2v1h16V3a2 2 0 0 0-2-2h-1V.5a.5.5 0 0 0-1 0V1H4V.5zM16 14V5H0v9a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2zm-5.146-5.146-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708.708z"
										></path>
									</svg>
									{{events.scheduled_on}}
								</a>
							</h6>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
	<div class="container mx-auto" id="event">
		<h1 class="fw-bolder text-center my-3">
			Take a look at our previous event.
		</h1>
		<div
			class="event-category mx-auto d-flex justify-content-evenly flex-wrap my-5"
		>
			<a
				type="button"
				class="btn btn-outline-primary rounded-pill px-5 my-2"
				href="{% url 'home'%}"
				>Show All</a
			>
			<a
				type="button"
				class="btn btn-outline-primary rounded-pill px-5 my-2"
				href="{% url 'home-category' 'tech-talks'%}"
				>Tech Talks</a
			>
			<a
				type="button"
				class="btn btn-outline-primary rounded-pill px-5 my-2"
				href="{% url 'home-category' 'freelancing'%}"
				>Freelancing</a
			>
			<a
				type="button"
				class="btn btn-outline-primary rounded-pill px-5 my-2"
				href="{% url 'home-category' 'content-creation'%}"
				>Content Creation</a
			>
			<a
				type="button"
				class="btn btn-outline-primary rounded-pill px-5 my-2"
				href="{% url 'home-category' 'finance'%}"
				>Finance</a
			>
			<a
				type="button"
				class="btn btn-outline-primary rounded-pill px-5 my-2"
				href="{% url 'home-category' 'entrepreneurship'%}"
				>Entrepreneurship</a
			>
		</div>
		<div class="upcoming-events">
			<div class="container">
				<div class="row">
					{% for events in past_events %}
					<div class="col-md-4 col-sm-12 col-xs-12 mx-auto">
						<div class="card my-2 mx-auto" style="width: 20rem">
							<img
								src="{{events.thumbnail.url}}"
								class="card-img-top"
								alt="..."
								style="height: 10rem; object-fit: cover"
							/>
							<div class="card-body">
								<h6 class="card-title" style="height: 3rem; overflow: hidden">
									{{events.title | truncatewords:7}}
								</h6>
								<!-- {% for hashtag in events.hashtags.all %} -->
									<a href="#">#{{hashtag}}</a>
								<!-- {% endfor %} -->
								<div class="d-grid gap-2">
									<button
										type="button"
										class="btn btn-outline-primary rounded-pill"
										data-bs-toggle="modal"
										data-bs-target="#videoModal"
										onClick="playvideo({{events.id | safe}})"
									>
										<svg
											xmlns="http://www.w3.org/2000/svg"
											width="16"
											height="16"
											fill="currentColor"
											class="bi bi-youtube"
											viewBox="0 0 16 16"
										>
											<path
												d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z"
											/>
										</svg>
										<span class="ms-1">Watch Now</span>
									</button>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>

<!-- modal -->
<div
	class="modal fade"
	id="videoModal"
	data-bs-backdrop="static"
	data-bs-keyboard="false"
>
	<div class="modal-dialog modal-dialog-centered modal-lg">
		<div class="modal-content">
			<button
				type="button"
				class="btn btn-danger close-btn"
				aria-label="Close"
				data-bs-dismiss="modal"
				style="position: absolute; top: -3rem; right: 0"
			>
				<span>Close</span>
			</button>
			<div class="modal-body p-0">
				<div class="ratio ratio-16x9">
					<iframe
						src=""
						title="YouTube video player"
						frameborder="0"
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
						allowfullscreen
						id="video"
					></iframe>
				</div>
			</div>
		</div>
	</div>
</div>
{% block script %}

<script>
	function playvideo(id){
		{% for events in past_events %}
		if ('{{events.id | safe}}'  == id ) {
			document.getElementById("video").src ="https://www.youtube.com/embed/{{events.video_id}}?enablejsapi=1"
		}
		{% endfor %}


	}
</script>
{% endblock script %}
<!-- modal end -->

{% endblock content %}